from app.models.producto import Producto
from app.models.cliente import Cliente
from app.models.detallefactura import Detallefactura
from app.models.factura import Factura
from app.models.carrito import Carrito
from app.models.categoria import Categoria
from app.models.proveedor import Proveedor
from app.models.metodopago import Metodopago
from app.models.personal import Personal